name = "rolldorado-app-com-de"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=rolldorado-app.com.de"
HMAC_KEY = "630fdb6dceb9b2f8660dd1f54d74c03a539dd854f7b20613ddc059ce508118fd"
COOKIE_NAME = "k9k"
PLAY_PATH = "discover"
BUTTON_ID = "p85056f0d2df920eb973cedcfc6fbf415"
GATE_SALT = "3352d788e6fadef8"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "cgt3"
CTA_SELECTOR = ".play-button"
